print ("Tugas python")
print ()
nama = input ("Billy Alfauzi Caesar")
pangilan = input ("BillY")
nim = input ("312110153")
tglhr = input ("26 januari")
tmptlhr = input ("Bekasi")
tlpn = input ("088219718992")
almt = input ("Kp.pasir konci Des.Pasir sari")
umur = input ("20")
print ()
print ("assalamualaikum")
print ()
print ("Let me introduce my self, my name is Billy Alfauzi Caesar, you can call me Billy,my nim is 312110153,i was born in Bekasi and i am 20 years old, my house in kp.pasir konci")
print ()
print ("thankyou")